version: '3.7'

services:
  postgres:
    image: postgres:15
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hF3EAGv9dCs
    volumes:
      - /home/pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    container_name: db
  bot:
    build: .
    command: sh -c 'python -m app'
    env_file:
      - ./.env
    volumes:
      - /home/data:/app/data
    restart: always
    depends_on:
      - postgres
    container_name: bot

volumes:
  pgdata:
